"""Generate synthetic PDB files for demo mode."""
import numpy as np

AA_LIST_3 = ['ALA','ARG','ASN','ASP','CYS','GLU','GLN','GLY','HIS','ILE',
             'LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL']

def _helix_coords(n_residues, rise=1.5, radius=2.3, turn=100.0):
    """Generate helix coordinates (roughly alpha-helix geometry)."""
    coords = []
    for i in range(n_residues):
        theta = np.deg2rad(turn * i)
        x = radius * np.cos(theta)
        y = radius * np.sin(theta)
        z = rise * i
        coords.append([x, y, z])
    return np.array(coords)

def _build_pdb_string(coords, residues, chain="A"):
    """Construct a minimal PDB string with CA atoms only."""
    lines = ["HEADER    SYNTHETIC PROTEIN", "TITLE     GENERATED BY PROTEINSCOPE"]
    atom_idx = 1
    for i, ((x, y, z), resname) in enumerate(zip(coords, residues), start=1):
        line = (f"ATOM  {atom_idx:5d}  CA  {resname} {chain}{i:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00 20.00           C")
        lines.append(line)
        atom_idx += 1
    lines.append("TER")
    lines.append("END")
    return "\n".join(lines)

def generate_synthetic_pair(n_residues=120, mutation_rate=0.10,
                            noise_sigma=2.0, seed=42):
    """Generate (reference_pdb_str, variant_pdb_str)."""
    rng = np.random.default_rng(seed)

    coords_ref = _helix_coords(n_residues)
    res_ref = [AA_LIST_3[rng.integers(0, 20)] for _ in range(n_residues)]
    pdb_ref = _build_pdb_string(coords_ref, res_ref)

    # Variant: perturb coordinates + mutate AAs at random positions
    coords_var = coords_ref.copy()
    res_var = res_ref.copy()
    n_mut = int(n_residues * mutation_rate)
    mut_positions = rng.choice(n_residues, size=n_mut, replace=False)
    for pos in mut_positions:
        coords_var[pos] += rng.normal(0, noise_sigma, size=3)
        # mutate to a random different AA
        new_aa = AA_LIST_3[rng.integers(0, 20)]
        while new_aa == res_ref[pos]:
            new_aa = AA_LIST_3[rng.integers(0, 20)]
        res_var[pos] = new_aa

    # add small global noise
    coords_var += rng.normal(0, 0.15, size=coords_var.shape)
    pdb_var = _build_pdb_string(coords_var, res_var)
    return pdb_ref, pdb_var